const {test}=require('node:test');
const assert=require('node:assert/strict');
const core=require('../cotejo-core.js'),extra=require('../extraccion.js');
const doc={cedula:'12345672',nombre:'ANA MARIA',apellido:'PEREZ GOMEZ',sexo:'F',fnac:'1980-04-05',vencimiento:'2030-01-01',pais_documento:'Uruguay'};
const plan={cedula:doc.cedula,nombre:'Ana',apellido:'Pérez',sexo:'F',fnac:doc.fnac,fecha:'2026-10-04',hora:'12:00:00'};
function run(d={},p={},options={}){return core.comparar([{...doc,...d}],[{...plan,...p}],options)[0];}
test('coincidencia con nombres abreviados por palabras completas',()=>assert.equal(run().estado,'ok'));
test('un nombre diferente nunca queda OK',()=>assert.equal(run({}, {nombre:'Lucía'}).estado,'error'));
test('prefijos parciales no acreditan apellidos',()=>assert.equal(core.compatibles('Pere','Perez Gomez'),false));
test('apellido vacío no acredita coincidencia',()=>assert.equal(run({apellido:''}).estado,'warn'));
test('nacimiento se coteja sin copiar fecha de ingreso',()=>assert.equal(run({}, {fnac:'1980-10-04'}).estado,'error'));
test('fecha imposible no se compara como válida',()=>assert.equal(core.fecha('2026-02-31'),''));
test('sexo ausente no se infiere',()=>assert.match(run({sexo:''}).obs,/Sexo sin verificar/));
test('vencimiento se compara al ingreso histórico',()=>assert.equal(run({vencimiento:'2026-10-05'},{},{hoy:'2026-10-08'}).estado,'ok'));
test('vencimiento ausente es diferente de sin vencimiento',()=>{assert.equal(run({vencimiento:''}).estado,'warn');assert.equal(run({vencimiento:'',sin_vencimiento:true}).estado,'ok');});
test('residente extranjero con CI uruguaya no cambia tipo por nacionalidad',()=>assert.equal(run({nacionalidad:'COLOMBIANA'}).estado,'ok'));
test('dos documentos con mismo número son ambiguos',()=>assert.match(core.comparar([doc,{...doc,nombre:'OTRA'}],[plan])[0].obs,/Varios documentos/));
test('visitas repetidas incluso idénticas se conservan',()=>assert.equal(core.comparar([doc],[plan,{...plan}]).length,2));
test('documento sin número no desaparece',()=>assert.equal(core.comparar([{...doc,cedula:''}],[]).length,1));
test('lectura parcial impide OK',()=>assert.equal(run({},{},{completa:false}).estado,'warn'));
test('lectura parcial no afirma ausencia de planilla',()=>assert.equal(core.comparar([doc],[],{completa:false})[0].estado,'warn'));
test('número distinto con nombre compatible pide revisar',()=>assert.match(run({cedula:'23456789'}).obs,/número distinto/));
test('preserva letras y ceros, sin confundir O y 0',()=>{assert.equal(core.numero('AB 001.234-5'),'AB0012345');assert.notEqual(core.numero('O123'),core.numero('0123'));});
test('JSON truncado no se convierte en []',()=>assert.throws(()=>extra.parsear('[{"cedula":"123')));
test('objeto válido se valida sin perder campos',()=>assert.equal(extra.validar({registros:[doc],lectura_completa:true,advertencias:[]}).lectura_completa,true));
test('array legado requiere revisión',()=>assert.equal(extra.validar([doc]).lectura_completa,false));
test('cédula numérica del modelo se rechaza para evitar pérdida de ceros',()=>assert.throws(()=>extra.validar({registros:[{...doc,cedula:12345672}],lectura_completa:true,advertencias:[]})));
test('registros ilegibles se conservan y dejan lectura parcial',()=>{const r=extra.validar({registros:[{}],lectura_completa:true,advertencias:[]});assert.equal(r.registros.length,1);assert.equal(r.lectura_completa,false);});
test('no valida una advertencia como lectura completa',()=>assert.equal(extra.validar({registros:[doc],lectura_completa:true,advertencias:['fila ilegible']}).lectura_completa,false));
